name: Release Workflow
run-name: Release tags
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [patch, minor, major]
        required: true
        description: Bump to patch, minor, or major version
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release new tag
    timeout-minutes: 1
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - env:
          USERNAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          BUMP_LEVEL: ${{ inputs.bump-level }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${USERNAME}"
          git config user.email "${EMAIL}"
          version="$(bash .github/scripts/bump.sh "${BUMP_LEVEL}")"
          gh release create "${version}" --title "${version}" --generate-notes
