name: Test action
run-name: test action
on:
#  pull_request:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    timeout-minutes: 1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: date > foo.md

      - name: Exercise
        id: exercise
        uses: ./
        with:
          message: Test

      - name: Verify
        run: |
          set -x
          test "$(gh pr view ${BRANCH} --json title --jq .title)" = "Test"
        env:
          BRANCH: ${{ steps.exercise.outputs.branch }}

      - name: Teardown
        if: ${{ always() }}
        run: |
          gh pr close "${BRANCH}" || true
          git push origin "${BRANCH}" --delete || true
        env:
          BRANCH: ${{ steps.exercise.outputs.branch }}

